### ISSUE TITLE
Example of config.js

### ISSUE THREAD

**Issue by longnguyen11288** [HospitalRun/frontend#101]
I'm trying to run this locally and getting 
```
$ ember serve
version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
Cannot find module '../config.js'
Error: Cannot find module '../config.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/lnguyen/oss/frontend/server/routes/couchproxy.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by jkleinsc** [comment]
You need to copy the server/config-example.js to server/config.js.
